name: provision

on:
  push:
    branches:
    - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  check:
    runs-on: ubuntu-latest
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      uses: yhwang/infra-provisioner@v1
      with:
        param1: 'myparam'
